
INSERT INTO artist(artistName) VALUES ('Billie Eilish');
INSERT INTO artist(artistName) VALUES ('Mac Miller');
INSERT INTO artist(artistName) VALUES ('Awolnation');
INSERT INTO artist(artistName) VALUES ('Lady Gaga');
INSERT INTO artist(artistName) VALUES ('Ariana Grande');
INSERT INTO artist(artistName) VALUES ('Amy Winehouse');
INSERT INTO artist(artistName) VALUES ('The Church');
INSERT INTO artist(artistName) VALUES ('Finneas');
INSERT INTO artist(artistName) VALUES ('Alexander Split');
INSERT INTO artist(artistName) VALUES ('Aaron Bruno');
INSERT INTO artist(artistName) VALUES ('Tommy Brown');
INSERT INTO artist(artistName) VALUES ('Mark Ronson');
INSERT INTO artist(artistName) VALUES ('Chris Gilbey');

INSERT INTO label(labelName) VALUES ('Interscope Records');
INSERT INTO label(labelName) VALUES ('Warner Records');
INSERT INTO label(labelName) VALUES ('Red Bull Records');
INSERT INTO label(labelName) VALUES ('Republic Records');
INSERT INTO label(labelName) VALUES ('Universal Island Records');
INSERT INTO label(labelName) VALUES ('EMI Recorded Music Australia');

INSERT INTO tag(tagName) VALUES ('inspirational');
INSERT INTO tag(tagName) VALUES ('sad');
INSERT INTO tag(tagName) VALUES ('empowering');
INSERT INTO tag(tagName) VALUES ('happy');
INSERT INTO tag(tagName) VALUES ('chill');
INSERT INTO tag(tagName) VALUES ('goth');
INSERT INTO tag(tagName) VALUES ('pop');
INSERT INTO tag(tagName) VALUES ('soul');
INSERT INTO tag(tagName) VALUES ('cool');

INSERT INTO roles(roleName) VALUES ('Creator');
INSERT INTO roles(roleName) VALUES ('Contribuitor');

INSERT INTO registeredusers(username, useremail) VALUES ('hellouser1', 'hellouser1@icloud.com');
INSERT INTO registeredusers(username, useremail) VALUES ('user28', 'u28@hotmail.com');
INSERT INTO registeredusers(username, useremail) VALUES ('rterlsha', 'ahslretr@yahoo.ca');
INSERT INTO registeredusers(username, useremail) VALUES ('ulsturib', 'ulstur@gmail.com' );
INSERT INTO registeredusers(username, useremail) VALUES ('ioritype', 'iori@yahoo.com');
INSERT INTO registeredusers(username, useremail) VALUES ('timulayt', "timu@shaw.ca");
INSERT INTO registeredusers(username, useremail) VALUES ('gercento', 'gerryct@telus.net');
INSERT INTO registeredusers(username, useremail) VALUES ('kashvi22', 'kashvi22@gmail.com');
INSERT INTO registeredusers(username, useremail) VALUES ('tegrahhhh', 'tegrahhh@gmail.com');
INSERT INTO registeredusers(username, useremail) VALUES ('devTo37', 'devto@outlook.com');
INSERT INTO registeredusers(username, useremail) VALUES ('mcbashed', 'bash@icloud.com');
INSERT INTO registeredusers(username, useremail) VALUES ('ryan2920', 'ryan@hotmail.com');

INSERT INTO album(albumTitle, releaseyear) VALUES ('When We All Fall Asleep, Where Do We Go?', 2019);
INSERT INTO album(albumTitle, releaseyear) VALUES ('Circles', 2020);
INSERT INTO album(albumTitle, releaseyear) VALUES ('Run', 2015);
INSERT INTO album(albumTitle, releaseyear) VALUES ('The Fame', 2008);
INSERT INTO album(albumTitle, releaseyear) VALUES ('Chromatica', 2020);
INSERT INTO album(albumTitle, releaseyear) VALUES ('thank u, next', 2019);
INSERT INTO album(albumTitle, releaseyear) VALUES ('Back To Black', 2006);
INSERT INTO album(albumTitle, releaseyear) VALUES ('dont smile at me', 2017);
INSERT INTO album(albumTitle, releaseyear) VALUES ('Of Skins and Heart', 1981);

INSERT INTO song(songtitle) VALUES ('!!!!!!!');
INSERT INTO song(songtitle) VALUES ('bad guy');
INSERT INTO song(songtitle) VALUES ('xanny');
INSERT INTO song(songtitle) VALUES ('you should see me in a crown');
INSERT INTO song(songtitle) VALUES ('all the good girls go to hell');
INSERT INTO song(songtitle) VALUES ('wish you were gay');
INSERT INTO song(songtitle) VALUES ("when the party's over");
INSERT INTO song(songtitle) VALUES ('8');
INSERT INTO song(songtitle) VALUES ('my strange addiction');
INSERT INTO song(songtitle) VALUES ('bury a friend');
INSERT INTO song(songtitle) VALUES ('ilomilo');
INSERT INTO song(songtitle) VALUES ('listen before i go');
INSERT INTO song(songtitle) VALUES ('i love you');
INSERT INTO song(songtitle) VALUES ('goodbye');

INSERT INTO song(songtitle) VALUES ('circles');
INSERT INTO song(songtitle) VALUES ('complicated');
INSERT INTO song(songtitle) VALUES ('blue world');
INSERT INTO song(songtitle) VALUES ('good news');
INSERT INTO song(songtitle) VALUES ('i can see');
INSERT INTO song(songtitle) VALUES ('everybody');
INSERT INTO song(songtitle) VALUES ('woods');
INSERT INTO song(songtitle) VALUES ('hand me downs');
INSERT INTO song(songtitle) VALUES ("that's on me");
INSERT INTO song(songtitle) VALUES ('hands');
INSERT INTO song(songtitle) VALUES ('surf');
INSERT INTO song(songtitle) VALUES ('once a day');

INSERT INTO song(songtitle) VALUES ('run');
INSERT INTO song(songtitle) VALUES ('fat face');
INSERT INTO song(songtitle) VALUES ('hollow moon (bad wolf)');
INSERT INTO song(songtitle) VALUES ('jailbreak');
INSERT INTO song(songtitle) VALUES ('kookseverywhere!!!');
INSERT INTO song(songtitle) VALUES ('i am');
INSERT INTO song(songtitle) VALUES ('headrest for my soul');
INSERT INTO song(songtitle) VALUES ('dreamers');
INSERT INTO song(songtitle) VALUES ('windows');
INSERT INTO song(songtitle) VALUES ('holy roller');
INSERT INTO song(songtitle) VALUES ('woman woman');
INSERT INTO song(songtitle) VALUES ('lie love live love');
INSERT INTO song(songtitle) VALUES ('like people, like plastic');
INSERT INTO song(songtitle) VALUES ('drinking lightning');

INSERT INTO song(songtitle) VALUES ('just dance');
INSERT INTO song(songtitle) VALUES ('lovegame');
INSERT INTO song(songtitle) VALUES ('paparazzi');
INSERT INTO song(songtitle) VALUES ('poker face');
INSERT INTO song(songtitle) VALUES ('eh, eh, (nothing else i can say)');
INSERT INTO song(songtitle) VALUES ('beautiful, dirty, rich');
INSERT INTO song(songtitle) VALUES ('the fame');
INSERT INTO song(songtitle) VALUES ('money honey');
INSERT INTO song(songtitle) VALUES ('starstruck');
INSERT INTO song(songtitle) VALUES ('boys boys boys');
INSERT INTO song(songtitle) VALUES ('paper gangsta');
INSERT INTO song(songtitle) VALUES ('brown eyes');
INSERT INTO song(songtitle) VALUES ('i like it rough');
INSERT INTO song(songtitle) VALUES ('summerboy');
INSERT INTO song(songtitle) VALUES ('disco heaven');

INSERT INTO song(songtitle) VALUES ('chromatica i');
INSERT INTO song(songtitle) VALUES ('alice');
INSERT INTO song(songtitle) VALUES ('stupid love');
INSERT INTO song(songtitle) VALUES ('rain on me (with ariana grande)');
INSERT INTO song(songtitle) VALUES ('free woman');
INSERT INTO song(songtitle) VALUES ('fun tonight');
INSERT INTO song(songtitle) VALUES ('chromatica ii');
INSERT INTO song(songtitle) VALUES ('911');
INSERT INTO song(songtitle) VALUES ('plastic doll');
INSERT INTO song(songtitle) VALUES ('sour candy (with blackpink)');
INSERT INTO song(songtitle) VALUES ('enigma');
INSERT INTO song(songtitle) VALUES ('replay');
INSERT INTO song(songtitle) VALUES ('chromatica iii');
INSERT INTO song(songtitle) VALUES ('sine from above (with elton john)');
INSERT INTO song(songtitle) VALUES ('1000 doves');
INSERT INTO song(songtitle) VALUES ('babylon');

INSERT INTO song(songtitle) VALUES ('imagine');
INSERT INTO song(songtitle) VALUES ('needy');
INSERT INTO song(songtitle) VALUES ('nasa');
INSERT INTO song(songtitle) VALUES ('bloodline');
INSERT INTO song(songtitle) VALUES ('fake smile');
INSERT INTO song(songtitle) VALUES ('bad idea');
INSERT INTO song(songtitle) VALUES ('make up');
INSERT INTO song(songtitle) VALUES ('ghostin');
INSERT INTO song(songtitle) VALUES ('in my head');
INSERT INTO song(songtitle) VALUES ('7 rings');
INSERT INTO song(songtitle) VALUES ('thank u, next');
INSERT INTO song(songtitle) VALUES ("break up with your girlfirend, i'm bored");

INSERT INTO song(songtitle) VALUES ('rehab');
INSERT INTO song(songtitle) VALUES ("you know i'm no good");
INSERT INTO song(songtitle) VALUES ('me & mr jones');
INSERT INTO song(songtitle) VALUES ('just friends');
INSERT INTO song(songtitle) VALUES ('back to black');
INSERT INTO song(songtitle) VALUES ('love is a losing game');
INSERT INTO song(songtitle) VALUES ('tears dry on their own');
INSERT INTO song(songtitle) VALUES ('wake up alone');
INSERT INTO song(songtitle) VALUES ('some unholy war');
INSERT INTO song(songtitle) VALUES ('he can only hold her');
INSERT INTO song(songtitle) VALUES ('addicted');

INSERT INTO song(songtitle) VALUES ('copycat');
INSERT INTO song(songtitle) VALUES ('idontwannabeyouanymore');
INSERT INTO song(songtitle) VALUES ('my boy');
INSERT INTO song(songtitle) VALUES ('watch');
INSERT INTO song(songtitle) VALUES ('party favor');
INSERT INTO song(songtitle) VALUES ('bellyache');
INSERT INTO song(songtitle) VALUES ('ocean eyes');
INSERT INTO song(songtitle) VALUES ('hostage');
INSERT INTO song(songtitle) VALUES ('&burn (with vince staples)');

INSERT INTO song(songtitle) VALUES ("for a moment we're strangers");
INSERT INTO song(songtitle) VALUES ("chrome injury");
INSERT INTO song(songtitle) VALUES ("the unguarded moment");
INSERT INTO song(songtitle) VALUES ("memories in future tense");
INSERT INTO song(songtitle) VALUES ("bel-air");
INSERT INTO song(songtitle) VALUES ("is this where you live");
INSERT INTO song(songtitle) VALUES ("she never said");
INSERT INTO song(songtitle) VALUES ("fighter pilot... korean war");
INSERT INTO song(songtitle) VALUES ("don't open the door to strangers");
INSERT INTO song(songtitle) VALUES ("in a heartbeat");
INSERT INTO song(songtitle) VALUES ("busdriver");

INSERT INTO producedby(artistId, producerId) VALUES (1,8);
INSERT INTO producedby(artistId, producerId) VALUES (2,9);
INSERT INTO producedby(artistId, producerId) VALUES (3,10);
INSERT INTO producedby(artistId, producerId) VALUES (4,12);
INSERT INTO producedby(artistId, producerId) VALUES (6,12);
INSERT INTO producedby(artistId, producerId) VALUES (7,8);

INSERT INTO userroles(userId, roleid) VALUES (1,2);
INSERT INTO userroles(userId, roleid) VALUES (2,2);
INSERT INTO userroles(userId, roleid) VALUES (3,2);
INSERT INTO userroles(userId, roleid) VALUES (4,2);
INSERT INTO userroles(userId, roleid) VALUES (5,1);
INSERT INTO userroles(userId, roleid) VALUES (6,1);
INSERT INTO userroles(userId, roleid) VALUES (7,2);
INSERT INTO userroles(userId, roleid) VALUES (8,1);
INSERT INTO userroles(userId, roleid) VALUES (9,1);
INSERT INTO userroles(userId, roleid) VALUES (10,1);
INSERT INTO userroles(userId, roleid) VALUES (11,2);
INSERT INTO userroles(userId, roleid) VALUES (12,2);

INSERT INTO artistTags(tagId, artistId) VALUES (7,1);
INSERT INTO artistTags(tagId, artistId) VALUES (7,4);
INSERT INTO artistTags(tagId, artistId) VALUES (6,4);
INSERT INTO artistTags(tagId, artistId) VALUES (8,6);
INSERT INTO artistTags(tagId, artistId) VALUES (8,12);
INSERT INTO artistTags(tagId, artistId) VALUES (7,5);

INSERT INTO songTags(tagId, songId) VALUES (7,2);
INSERT INTO songTags(tagId, songId) VALUES (7,41);
INSERT INTO songTags(tagId, songId) VALUES (1,63);
INSERT INTO songTags(tagId, songId) VALUES (2,88);
INSERT INTO songTags(tagId, songId) VALUES (8,88);

INSERT INTO albumTags(tagId, albumId) VALUES (7,1);
INSERT INTO albumTags(tagId, albumId) VALUES (7,4);
INSERT INTO albumTags(tagId, albumId) VALUES (7,5);
INSERT INTO albumTags(tagId, albumId) VALUES (7,6);
INSERT INTO albumTags(tagId, albumId) VALUES (8,7);
INSERT INTO albumTags(tagId, albumId) VALUES (9,1);
INSERT INTO albumTags(tagId, albumId) VALUES (9,2);
INSERT INTO albumTags(tagId, albumId) VALUES (9,3);
INSERT INTO albumTags(tagId, albumId) VALUES (9,4);
INSERT INTO albumTags(tagId, albumId) VALUES (9,5);
INSERT INTO albumTags(tagId, albumId) VALUES (9,6);
INSERT INTO albumTags(tagId, albumId) VALUES (9,7);
INSERT INTO albumTags(tagId, albumId) VALUES (9,8);
INSERT INTO albumTags(tagId, albumId) VALUES (9,9);

INSERT INTO albumLabel(albumId, labelId) VALUES (1,1);
INSERT INTO albumLabel(albumId, labelId) VALUES (2,2);
INSERT INTO albumLabel(albumId, labelId) VALUES (3,3);
INSERT INTO albumLabel(albumId, labelId) VALUES (4,1);
INSERT INTO albumLabel(albumId, labelId) VALUES (5,1);

INSERT INTO artistSongs(artistId, songId) VALUES (1,1);
INSERT INTO artistSongs(artistId, songId) VALUES (1,2);
INSERT INTO artistSongs(artistId, songId) VALUES (1,3);
INSERT INTO artistSongs(artistId, songId) VALUES (1,4);
INSERT INTO artistSongs(artistId, songId) VALUES (1,5);
INSERT INTO artistSongs(artistId, songId) VALUES (1,6);
INSERT INTO artistSongs(artistId, songId) VALUES (1,7);
INSERT INTO artistSongs(artistId, songId) VALUES (1,8);
INSERT INTO artistSongs(artistId, songId) VALUES (1,9);
INSERT INTO artistSongs(artistId, songId) VALUES (1,10);
INSERT INTO artistSongs(artistId, songId) VALUES (1,11);
INSERT INTO artistSongs(artistId, songId) VALUES (1,12);
INSERT INTO artistSongs(artistId, songId) VALUES (1,13);
INSERT INTO artistSongs(artistId, songId) VALUES (1,14);

INSERT INTO artistAlbums(artistId, albumId) VALUES (1,1);
INSERT INTO artistAlbums(artistId, albumId) VALUES (2,2);
INSERT INTO artistAlbums(artistId, albumId) VALUES (3,3);
INSERT INTO artistAlbums(artistId, albumId) VALUES (4,4);
INSERT INTO artistAlbums(artistId, albumId) VALUES (4,5);
INSERT INTO artistAlbums(artistId, albumId) VALUES (5,6);
INSERT INTO artistAlbums(artistId, albumId) VALUES (6,7);
INSERT INTO artistAlbums(artistId, albumId) VALUES (1,8);
INSERT INTO artistAlbums(artistId, albumId) VALUES (7,9);

INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,1,1);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,2,2);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,3,3);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,4,4);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,5,5);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,6,6);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,7,7);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,8,8);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,9,9);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,10,10);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,11,11);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,12,12);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,13,13);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (1,14,14);

INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (2,15,1);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (2,16,2);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (2,17,3);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (2,18,4);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (2,19,5);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (2,20,6);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (2,21,7);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (2,22,8);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (2,23,9);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (2,24,10);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (2,25,11);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (2,26,12);

INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,27,1);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,28,2);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,29,3);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,30,4);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,31,5);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,32,6);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,33,7);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,34,8);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,35,9);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,36,10);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,37,11);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,38,12);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,39,13);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (3,40,14);

INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,41,1);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,42,2);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,43,3);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,44,4);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,45,5);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,46,6);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,47,7);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,48,8);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,49,9);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,50,10);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,51,11);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,52,12);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,53,13);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,54,14);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (4,55,15);

INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,56,1);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,57,2);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,58,3);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,59,4);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,60,5);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,61,6);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,62,7);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,63,8);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,64,9);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,65,10);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,66,11);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,67,12);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,68,13);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,69,14);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,70,15);
INSERT INTO albumSongs(albumId, songId, songNumber) VALUES (5,71,16);

